
import java.sql.Date;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acv
 */
public class RoomSchedulerFrame extends javax.swing.JFrame
{
    private ReservationQueries rq;
    private RoomQueries RoomQ;
    
    /**
     * Creates new form RoomSchedulerFrame
     */
    public RoomSchedulerFrame()
    {
        initComponents();
        rq= new ReservationQueries();
        RoomQ= new RoomQueries();
        // Load the combo boxes with data.
        rebuildFacultyComboBoxes();
    }
    
    public void rebuildFacultyComboBoxes()
    {
        reserveFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));    
        cancelFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        chooseFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
    }
    public void displayText(){
        displayResArea.setText(rq.displayReservation());
        displayWaitlistArea.setText(rq.getWaitlist_list());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        waitlistPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addFacultyTextField = new javax.swing.JTextField();
        addFacultyButton = new javax.swing.JButton();
        addFacultyStatusLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RoomTab = new javax.swing.JTabbedPane();
        addRoomTab = new javax.swing.JPanel();
        roomSeatsLabel = new javax.swing.JLabel();
        addRoomLabel = new javax.swing.JLabel();
        roomSeatsTextField = new javax.swing.JTextField();
        addRoomTextField = new javax.swing.JTextField();
        addRoomButton = new javax.swing.JButton();
        addRoomStatusLabel = new javax.swing.JLabel();
        waitlistResLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        submitDropRoomBut = new javax.swing.JButton();
        dropRoomTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dropRoomLabel = new javax.swing.JLabel();
        addDateTab = new javax.swing.JPanel();
        addDateLabel1 = new javax.swing.JLabel();
        AddDateButton = new javax.swing.JButton();
        DateSpinner = new javax.swing.JSpinner();
        addDateStatusLabel = new javax.swing.JLabel();
        ReservePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reserveFacultyComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        reserveDateComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        reserveSeatsTextField = new javax.swing.JTextField();
        reserveSubmitButton = new javax.swing.JButton();
        reserveStatusLabel = new javax.swing.JLabel();
        CancelResTab = new javax.swing.JPanel();
        cancelResButton = new javax.swing.JButton();
        cancelFacultyComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cancelDateComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cancelResLabel = new javax.swing.JLabel();
        waitlistUpdateLabel = new javax.swing.JLabel();
        StatusTab = new javax.swing.JTabbedPane();
        showReservationTab = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayResArea = new javax.swing.JTextArea();
        showWaitlistTab = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayWaitlistArea = new javax.swing.JTextArea();
        showFacultyTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayFacultyArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        chooseFacultyComboBox = new javax.swing.JComboBox<>();
        chooseFacultySubmitBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Room Scheduler");

        jLabel2.setText("Add Faculty Name: ");

        addFacultyTextField.setColumns(20);

        addFacultyButton.setText("Submit");
        addFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyButtonActionPerformed(evt);
            }
        });

        addFacultyStatusLabel.setText("    ");

        jLabel7.setText("   ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addFacultyStatusLabel)
                                    .addComponent(jLabel7)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(addFacultyButton)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addFacultyButton)
                .addGap(22, 22, 22)
                .addComponent(addFacultyStatusLabel)
                .addGap(242, 242, 242)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Add Faculty", jPanel1);

        roomSeatsLabel.setText("Seats:");

        addRoomLabel.setText("Add Room:");

        addRoomButton.setText("Submit");
        addRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addRoomTabLayout = new javax.swing.GroupLayout(addRoomTab);
        addRoomTab.setLayout(addRoomTabLayout);
        addRoomTabLayout.setHorizontalGroup(
            addRoomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRoomTabLayout.createSequentialGroup()
                .addGroup(addRoomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRoomTabLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(addRoomButton))
                    .addGroup(addRoomTabLayout.createSequentialGroup()
                        .addGroup(addRoomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addRoomTabLayout.createSequentialGroup()
                                .addGroup(addRoomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addRoomTabLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(addRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addRoomTabLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(roomSeatsLabel)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(addRoomTabLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(addRoomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addRoomTabLayout.createSequentialGroup()
                                        .addComponent(addRoomStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(71, 71, 71))
                                    .addGroup(addRoomTabLayout.createSequentialGroup()
                                        .addComponent(waitlistResLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))))
                        .addGroup(addRoomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addRoomTabLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(roomSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(368, 368, 368))
        );
        addRoomTabLayout.setVerticalGroup(
            addRoomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRoomTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addRoomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addRoomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomSeatsLabel)
                    .addComponent(roomSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(addRoomButton)
                .addGap(27, 27, 27)
                .addComponent(addRoomStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waitlistResLabel)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        RoomTab.addTab("Add Room", addRoomTab);

        submitDropRoomBut.setText("submit");
        submitDropRoomBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDropRoomButActionPerformed(evt);
            }
        });

        dropRoomTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropRoomTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Room to Drop:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(submitDropRoomBut))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addGap(36, 36, 36)
                        .addComponent(dropRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(dropRoomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(260, 260, 260)))
                .addGap(331, 331, 331))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addComponent(submitDropRoomBut)
                .addGap(18, 18, 18)
                .addComponent(dropRoomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(311, 311, 311))
        );

        RoomTab.addTab("Drop Room", jPanel2);

        waitlistPanel.addTab("Room", RoomTab);

        addDateLabel1.setText("Add Date:");

        AddDateButton.setText("Submit");
        AddDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDateButtonActionPerformed(evt);
            }
        });

        DateSpinner.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout addDateTabLayout = new javax.swing.GroupLayout(addDateTab);
        addDateTab.setLayout(addDateTabLayout);
        addDateTabLayout.setHorizontalGroup(
            addDateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDateTabLayout.createSequentialGroup()
                .addGroup(addDateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDateTabLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(addDateLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addDateTabLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(AddDateButton))
                    .addGroup(addDateTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addDateStatusLabel)))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        addDateTabLayout.setVerticalGroup(
            addDateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDateTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(addDateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDateLabel1)
                    .addComponent(DateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(AddDateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addDateStatusLabel)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Add Date", addDateTab);

        jLabel4.setText("Faculty: ");

        reserveFacultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveFacultyComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Date: ");

        jLabel6.setText("Seats Required: ");

        reserveSeatsTextField.setColumns(3);

        reserveSubmitButton.setText("Submit");
        reserveSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSubmitButtonActionPerformed(evt);
            }
        });

        reserveStatusLabel.setText("   ");

        javax.swing.GroupLayout ReservePanelLayout = new javax.swing.GroupLayout(ReservePanel);
        ReservePanel.setLayout(ReservePanelLayout);
        ReservePanelLayout.setHorizontalGroup(
            ReservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reserveStatusLabel)
                    .addGroup(ReservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ReservePanelLayout.createSequentialGroup()
                            .addGroup(ReservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(ReservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reserveSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ReservePanelLayout.createSequentialGroup()
                            .addComponent(reserveSubmitButton)
                            .addGap(26, 26, 26))))
                .addContainerGap(497, Short.MAX_VALUE))
        );
        ReservePanelLayout.setVerticalGroup(
            ReservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(reserveSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(reserveSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(reserveStatusLabel)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Reserve Room", ReservePanel);

        cancelResButton.setText("Submit");
        cancelResButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelResButtonActionPerformed(evt);
            }
        });

        cancelFacultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFacultyComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Faculty:");

        jLabel8.setText("Choose faculty and date that wished to cancel");

        jLabel9.setText("Date:");

        javax.swing.GroupLayout CancelResTabLayout = new javax.swing.GroupLayout(CancelResTab);
        CancelResTab.setLayout(CancelResTabLayout);
        CancelResTabLayout.setHorizontalGroup(
            CancelResTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelResTabLayout.createSequentialGroup()
                .addGroup(CancelResTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CancelResTabLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(CancelResTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CancelResTabLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(CancelResTabLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cancelResLabel)))
                    .addGroup(CancelResTabLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(cancelResButton))
                    .addGroup(CancelResTabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(waitlistUpdateLabel)))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        CancelResTabLayout.setVerticalGroup(
            CancelResTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelResTabLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CancelResTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CancelResTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(4, 4, 4)
                .addComponent(cancelResButton)
                .addGap(18, 18, 18)
                .addComponent(cancelResLabel)
                .addGap(18, 18, 18)
                .addComponent(waitlistUpdateLabel)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Cancel Reservation", CancelResTab);

        displayResArea.setColumns(20);
        displayResArea.setRows(5);
        jScrollPane1.setViewportView(displayResArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout showReservationTabLayout = new javax.swing.GroupLayout(showReservationTab);
        showReservationTab.setLayout(showReservationTabLayout);
        showReservationTabLayout.setHorizontalGroup(
            showReservationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showReservationTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        showReservationTabLayout.setVerticalGroup(
            showReservationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showReservationTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        StatusTab.addTab("Reservation", showReservationTab);

        displayWaitlistArea.setColumns(20);
        displayWaitlistArea.setRows(5);
        jScrollPane2.setViewportView(displayWaitlistArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout showWaitlistTabLayout = new javax.swing.GroupLayout(showWaitlistTab);
        showWaitlistTab.setLayout(showWaitlistTabLayout);
        showWaitlistTabLayout.setHorizontalGroup(
            showWaitlistTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(showWaitlistTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(showWaitlistTabLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        showWaitlistTabLayout.setVerticalGroup(
            showWaitlistTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(showWaitlistTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(showWaitlistTabLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        StatusTab.addTab("Waitlist", showWaitlistTab);

        displayFacultyArea.setColumns(20);
        displayFacultyArea.setRows(5);
        jScrollPane3.setViewportView(displayFacultyArea);

        jLabel11.setText("Choose Faculty");

        chooseFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chooseFacultySubmitBut.setText("Submit");
        chooseFacultySubmitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFacultySubmitButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showFacultyTabLayout = new javax.swing.GroupLayout(showFacultyTab);
        showFacultyTab.setLayout(showFacultyTabLayout);
        showFacultyTabLayout.setHorizontalGroup(
            showFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showFacultyTabLayout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addGroup(showFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showFacultyTabLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(36, 36, 36)
                        .addComponent(chooseFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showFacultyTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chooseFacultySubmitBut)
                .addGap(269, 269, 269))
        );
        showFacultyTabLayout.setVerticalGroup(
            showFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showFacultyTabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(showFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(chooseFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseFacultySubmitBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StatusTab.addTab("Faculty", showFacultyTab);

        waitlistPanel.addTab("Status", StatusTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(waitlistPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waitlistPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFacultyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addFacultyButtonActionPerformed
    {//GEN-HEADEREND:event_addFacultyButtonActionPerformed
        // Add the faculty to the faculty table.
        String name = addFacultyTextField.getText();
        Faculty.addFaculty(name);
        addFacultyStatusLabel.setText(name+" has been added to the Faculty.");
        reserveDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        // rebuild the reservation faculty combo box.
        rebuildFacultyComboBoxes();

    }//GEN-LAST:event_addFacultyButtonActionPerformed

    private void reserveFacultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveFacultyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveFacultyComboBoxActionPerformed

    private void reserveSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSubmitButtonActionPerformed
        //ReservationQueries rq= new ReservationQueries();
        //set Reservation Tab
        String faculty = reserveFacultyComboBox.getSelectedItem().toString();
        Date chose_date = (Date) reserveDateComboBox.getSelectedItem();
        String chose_seats = reserveSeatsTextField.getText();
        int chose_seats_int=Integer.parseInt(chose_seats);
        rq.addReservation(faculty, chose_date, chose_seats_int);
  
        displayText();
        reserveStatusLabel.setText(rq.ResStatus);
// TODO add your handling code here:
    }//GEN-LAST:event_reserveSubmitButtonActionPerformed

    private void AddDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDateButtonActionPerformed
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(DateSpinner.getValue());
        Date day = Date.valueOf(spinnerValue);
        Dates.addDate(day);
        reserveDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));

        addDateStatusLabel.setText(day+" has been added");// TODO add your handling code here:
    }//GEN-LAST:event_AddDateButtonActionPerformed

    private void addRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomButtonActionPerformed
        String roomName= addRoomTextField.getText();
        int roomSeats=Integer.parseInt(roomSeatsTextField.getText());
        RoomQ.addRoom(roomName, roomSeats);
        displayText();
        addRoomStatusLabel.setText("add "+roomName+" with "+roomSeats+ " seats");
        waitlistResLabel.setText(RoomQ.waitlistResString);
    }//GEN-LAST:event_addRoomButtonActionPerformed

    private void cancelFacultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFacultyComboBoxActionPerformed
 // TODO add your handling code here:
    }//GEN-LAST:event_cancelFacultyComboBoxActionPerformed

    private void cancelResButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelResButtonActionPerformed
        String faculty = cancelFacultyComboBox.getSelectedItem().toString();
        //cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        Date chose_date = (Date) cancelDateComboBox.getSelectedItem();
        rq.checkDelete(faculty, chose_date);
        displayText();
        cancelResLabel.setText(faculty+" in "+chose_date+" gets cancelled");
        waitlistUpdateLabel.setText(rq.moveWaitlistString);
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelResButtonActionPerformed

    private void dropRoomTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropRoomTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropRoomTextFieldActionPerformed

    private void submitDropRoomButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDropRoomButActionPerformed
        String room=dropRoomTextField.getText();
        RoomQ.dropRoom(room);
        dropRoomLabel.setText(RoomQ.dropRoomString);
        displayText();
    // TODO add your handling code here:
    }//GEN-LAST:event_submitDropRoomButActionPerformed

    private void chooseFacultySubmitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFacultySubmitButActionPerformed
        String faculty = chooseFacultyComboBox.getSelectedItem().toString();
        rq.displayResByfaculty(faculty);
        displayFacultyArea.setText(rq.displayfacultyString);
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseFacultySubmitButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {   
//              
                
                new RoomSchedulerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDateButton;
    private javax.swing.JPanel CancelResTab;
    private javax.swing.JSpinner DateSpinner;
    private javax.swing.JPanel ReservePanel;
    private javax.swing.JTabbedPane RoomTab;
    private javax.swing.JTabbedPane StatusTab;
    private javax.swing.JLabel addDateLabel1;
    private javax.swing.JLabel addDateStatusLabel;
    private javax.swing.JPanel addDateTab;
    private javax.swing.JButton addFacultyButton;
    private javax.swing.JLabel addFacultyStatusLabel;
    private javax.swing.JTextField addFacultyTextField;
    private javax.swing.JButton addRoomButton;
    private javax.swing.JLabel addRoomLabel;
    private javax.swing.JLabel addRoomStatusLabel;
    private javax.swing.JPanel addRoomTab;
    private javax.swing.JTextField addRoomTextField;
    private javax.swing.JComboBox<String> cancelDateComboBox;
    private javax.swing.JComboBox<String> cancelFacultyComboBox;
    private javax.swing.JButton cancelResButton;
    private javax.swing.JLabel cancelResLabel;
    private javax.swing.JComboBox<String> chooseFacultyComboBox;
    private javax.swing.JButton chooseFacultySubmitBut;
    private javax.swing.JTextArea displayFacultyArea;
    private javax.swing.JTextArea displayResArea;
    private javax.swing.JTextArea displayWaitlistArea;
    private javax.swing.JLabel dropRoomLabel;
    private javax.swing.JTextField dropRoomTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> reserveDateComboBox;
    private javax.swing.JComboBox<String> reserveFacultyComboBox;
    private javax.swing.JTextField reserveSeatsTextField;
    private javax.swing.JLabel reserveStatusLabel;
    private javax.swing.JButton reserveSubmitButton;
    private javax.swing.JLabel roomSeatsLabel;
    private javax.swing.JTextField roomSeatsTextField;
    private javax.swing.JPanel showFacultyTab;
    private javax.swing.JPanel showReservationTab;
    private javax.swing.JPanel showWaitlistTab;
    private javax.swing.JButton submitDropRoomBut;
    private javax.swing.JTabbedPane waitlistPanel;
    private javax.swing.JLabel waitlistResLabel;
    private javax.swing.JLabel waitlistUpdateLabel;
    // End of variables declaration//GEN-END:variables
}
